Model:
  name: RdfModel
  origin: store
  source: BlueBrainNexus
  context:
    iri: "https://bbp.neuroshapes.org"
    bucket: "neurosciencegraph/datamodels"
Store:
  name: BlueBrainNexus
  endpoint: https://bbp.epfl.ch/nexus/v1
  searchendpoints:
    sparql:
      endpoint: "https://bluebrain.github.io/nexus/vocabulary/defaultSparqlIndex"
    elastic:
      endpoint: "https://bbp.epfl.ch/neurosciencegraph/data/views/aggreg-es/dataset"
      mapping: "https://bbp.epfl.ch/neurosciencegraph/data/views/es/dataset"
      default_str_keyword_field: "keyword"
  vocabulary:
    metadata:
      iri: "https://bluebrain.github.io/nexus/contexts/metadata.json"
      local_iri: "https://bluebrainnexus.io/contexts/metadata.json"
    namespace: "https://bluebrain.github.io/nexus/vocabulary/"
    deprecated_property: "https://bluebrain.github.io/nexus/vocabulary/deprecated"
    project_property: "https://bluebrain.github.io/nexus/vocabulary/project"
  max_connection: 50
  versioned_id_template: "{x.id}?rev={x._store_metadata._rev}"
  file_resource_mapping: https://raw.githubusercontent.com/BlueBrain/nexus-forge/master/examples/configurations/nexus-store/file-to-resource-mapping.hjson

Resolvers:
  ontology:
    - resolver: OntologyResolver
      origin: store
      source: BlueBrainNexus
      targets:
        - identifier: terms
          bucket: neurosciencegraph/datamodels
      searchendpoints:
        sparql:
          endpoint: "https://bluebrain.github.io/nexus/vocabulary/defaultSparqlIndex"
      result_resource_mapping: https://raw.githubusercontent.com/BlueBrain/nexus-forge/master/examples/configurations/nexus-resolver/term-to-resource-mapping.hjson
  agent:
    - resolver: AgentResolver
      origin: store
      source: BlueBrainNexus
      targets:
        - identifier: agents
          bucket: bbp/agents
      searchendpoints:
        sparql:
          endpoint: "https://bluebrain.github.io/nexus/vocabulary/defaultSparqlIndex"
      result_resource_mapping: https://raw.githubusercontent.com/BlueBrain/nexus-forge/master/examples/configurations/nexus-resolver/agent-to-resource-mapping.hjson

Formatters:
  identifier: https://bbp.epfl.ch/neurosciencegraph/data/{}/{}
  identifier_neuroelectro: http://neuroelectro.org/api/1/{}/{}
  identifier_neurolex: http://neurolex.org/wiki/{}

Databases:
  UniProt:
    origin: store
    source: SPARQLStore
    endpoint: "http://purl.uniprot.org/core/"
    searchendpoints:
      sparql:
        endpoint: "https://sparql.uniprot.org/sparql"
    model: 
      origin: directory
      source: /Users/cgonzale/Documents/code/nexus-forge/examples/database-sources/UniProt
      context:
        iri: "https://bbp.epfl.ch/jsonldcontext/db/uniprot"
        bucket: jsonld_context.json
  NeuroElectro:
    origin: store
    source: BlueBrainNexus
    bucket: bbp/neuroelectro
    model:
      origin: directory
      source: /Users/cgonzale/Documents/code/nexus-forge/examples/database-sources/NeuroElectro
      context:
        bucket: jsonld_context.json
  MouseLight:
    origin: store
    source: BlueBrainNexus
    bucket: dke/kgforge
    model:
      origin: directory
      source: /Users/cgonzale/Documents/code/nexus-forge/examples/database-sources/MouseLight
      context:
        bucket: jsonld_context.json