language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .[dev]

script:
  - pytest --cov=./

after_success:
  - codecov

deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
  user: bbp.opensource
  password:
    secure: xR4Cl2xRPc+xhSbCSc1gVWWlkTDEyhhHLwFUyE/DVswfXTWoy9b5HIHrg/B8mFXqlJT3GLMs27F1grunN+AoqmQQQWpz3t1SwrQ00ug3InApMXqqyVo8UvEnHx/+mfmk7bnORG0E7sl4JrTeq4mDcZOWw7Q5l6vP4GWPXmchScF4guC4B3UX5g6Whc4gTpumb2bKftbp89guJa1myhBt5Q4IrF548e7VX08lH1SKRk0LU36kVEgfWf7Covlxz45hEcUyEkC8PQLQndBz+ydIk5OsWY2geaY4Rk/GU38ioQJSqUrJLzNGaIhYEUQOO90JAHVdaKVHb3xe3zkjhvOyZEHiGMbLWnEjA8dJJXFvVxAAL6GpmadzrOFnShIlCurJwv2JZZpxayUplAKxhgKr+VeHFsHxcg5qetUtVZy4bFXeBeTZcrGDPc+iHOndZf3pSNkbQGy3FmKPqUD/zvVg81c6jIB/P6YYb25oLghBMloU/nS28Xz3VenhMz/2OrxyvozU0AVEtYcdxB/5xlutLW81lvFEMa11KLtshmxzJdoUmwJuKm5Q7pU0RPtIRe6Kr3WuYShTKZo8afPuPt+0of8o/zFL1Nuc9XTSFq2qxN4GRUttzagNkGIeCu9KHX+UknwwQ5F6ArZPU5sRTBuGctd5Yyzrzfm8WSRC6emhwvc=
  skip_cleanup: true
