language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .

branches:
  only:
    - master

deploy:
  provider: pypi
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
  user: bbp.opensource
  password:
    secure: WvU3RrOW6gL2Gfblq7ZX5mtqCleFzaGO/ivAUcrd6GrCpG90j9xQRTJnQnFXve3AUuHKUzc3YwcBOSRmnv09BPfS8vaxmI3J4lF9EHXTPQ9WrAfeTDGBehKFXkQJx/1L1kt0eMJ2uVETizhp3NipTLWdOlzzWPV74Oos2M/7x4SVf9wF9QWK71P+c3wxnkYhsnb+WLGFlBA33Hr5VAs/ylmu8LuGErHDKWyaG8/yBHmhuJp1W6NZYbdm2H3eaq3Y649pT21IZ5f39CQ4+LuN+UWLIhM7ikqSnRs8x2//CBrRBW3tB1s6XOKelql0dvecYMGkPQhlfUxm2NlRlYmj37+FzT1qJh1O6OpZC35Vp55KAo97aSIMdCtKqXEZB7WuhZpsVxFleCZqss4DL+WoFFk55qb/KC1Y7hVG0HO2lBMtH39qFukkAupctuz09HIBEqGFuGD3mZvbJp+RlrdVZJJJjTP2xg9LhYtoOAYhLulO4QensHqNCQGFodUDFRLKX8vxUuMlZ7Of9Tru+7u5St6s4yhelq5hTu89J9f4jjL+LyiKkZj9TNfgk0slFnVWq9N/i/PUN0NcwvoD3YCiBomVuIU3+2GBE5c7Hco9cIU8RS+997PYMFXwlaOv1cEyO7tycBz3N1ifqFQTQzfNJ938oxAt8VM73/VDN7KPSmw=
