language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .[dev]

script:
  - pytest --cov=./

after_success:
  - codecov

deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
  user: bbp.opensource
  password:
    secure: yyTq54CGIy9xbljaaM3CGvm/mEOSOVxXYVm8tz7kUcosxyfjkvY4U7Jd0LwqhUObpDW1am8ki8zcyfAyq08zNCuTnfmx9cF/ry9za2I2Q6pu1liDBXQb1p2xyTtspZYXVAcqYkzDRdgPy7EE8/DOdcTu28fsfvmrOuoXq/w5Qau5gM/fFgcXVoUtL9cYOBk103AzNPLyXSof8Ap8INU3bc7fOgC6NF+7dEV8wEfIZ1sJmnAlbmjiF02Xjop6ILcrO5nyUpqR0SE8xfAsJAp6nc9syUqBZ0+1hCfnd2h5kqhqP0wxrww5esHbad0azblDEBplub3VBv9FoI+ZzjTYa/o8PWlQZ2vH9FjxAk+NusQHex6AYLVCWxmzNZInT7hFuE+pjT6XpGEAZb68NwGPWdA/Wgq5wzyuXBRmhfzXd8nl4HhtqhFO+hTVIqLPczoyoYZCeqG1bqH+0m7eOIWLff4hg9McrTgbWi419ySfbwyOeXkn2yJPLqDO4jFPG6IdS2KbB40Fbst1F1tCJTSdCxGj5Q7OFBxxC0bLdCzEIYuHgElLGfEPn7pp4ROWX51/YDKQETK+7hm1pG/icm2gLj396by8Wj/MnxaNp0Znoia5rFOQh5BnaFTr71MBbqtDBUmj/4V+PLXS9rgISR00z9+y2iCg7Ok6w+GoTRK1GNQ=
  skip_cleanup: true
