name: Test Forge
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run tests with pytest
        run: |
          pytest --cov=./
          codecov