name: Test Forge
on: [ push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run tests
        run: pytest --cov=./
